sudo: required
 
language: go 
go: 
  - "1.14.4" 

services: 
  - docker

before_install: 
  # login to docker registries (dockerhub + heroku) 
  - echo "$ DOCKER_PASSWORD" | docker login -u "$ DOCKER_USERNAME" --password-stdin

script: 
  - go build