sudo: required
 
language: go 
go: 
  - "1.14.4" 

services: 
  - docker

before_install: 
  # login to docker registries (dockerhub + heroku) 
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com


script: 
  - export PORT=8080
  - go test
  - go build
  - docker build -t manmohantarle/webapp .
  - docker tag manmohantarle/webapp registry.heroku.com/$HEROKU_APP_NAME/web

deploy:
  provider: script
  script:
   docker push manmohantarle/webapp;
   docker push registry.heroku.com/$HEROKU_APP_NAME/web;
   heroku container:release web --app $HEROKU_APP_NAME
  branch: master
