sudo: required
 
language: go 
go: 
  - "1.14.4" 

services: 
  - docker

before_install: 
  # login to docker registries (dockerhub + heroku) 
  - docker login --username="$DOCKER_USERNAME" --password="$DOCKER_PASSWORD"

script: 
  - go build
  - docker build -t webapp .
deploy:
  provider: script
  script:
   docker push manmohantarle/webapp:latest
  branch: master
